### PR TITLE
Make built field sizes configurable

### PR DESCRIPTION
**Pull request by sipa**
This adds a `--enable-fields=LIST` configure options, which takes a list of integers. The default is all supported field sizes (currently 2 through 64 inclusive). Binary sizes and compile time go down significantly when reducing the list.

### CODE REVIEW

**Comment by sipa** [comment]
@rustyrussell @naumenkogs you may be interested in this

**Comment by sipa** [comment]
@theuni Would you mind having a look at the build system changes?

**Comment by naumenkogs** [comment]
Concept ACK.
I'm not really qualified to judge this kind of optimizations properly, but code looks good to me.

**Comment by sipa** [comment]
FWIW there are a few more ways to reduce binary size further if reducing performance slightly is acceptable.

**Comment by gmaxwell** [comment]
Seems like a good idea.  My one reservation is that it's really awkward and bad form for the functionality offered by a library to change based on its compilation options... though minisketch is mini enough that it's hardly a library.

I wonder if it might be reasonable to create some kind of 'backup implementation' that lets the library work on all sizes but much slower without the template expansion and table bloat.   Then the argument could mostly be a fast-sizes + an option to disable the generic fallback for someone who is really space constrained.

**Comment by sipa** [comment]
It turns out that right now the binary size is around 3.5 MB for all 63 field sizes. When using 3-bit precomputed tables instead of 6-bit ones, that only reduces to 2.5 MB. So It seems most of the binary size is actually code, not tables.

**Comment by theuni** [comment]
@sipa Build changes look sane enough to me at a glance. Neat tricks :)

My only nit is that for projects that use minisketch without the buildsystem, with this change all field sizes are now off by default. Is it possible to reverse the logic?

Also, IMO if you really care about size you're probably linking this statically, in which case I would expect the linker to mostly eliminate the unused functions/types anyway?

**Comment by sipa** [comment]
@theuni That's a good point, maybe if nothing is configured, everything should be built? The linker won't eliminate things, except perhaps a very smart deeply inlining LTO could discovered these functions won't be called.

I'm working on another change first that should permit having slow support for all field sizes with little code, so that disabling things doesn't lead to too surprising results when linking a shared lib.

**Comment by gmaxwell** [comment]
Probably the default should be all on. Then setting the option overrides with a list.

**Comment by sipa** [comment]
@gmaxwell The default is already everything on, but only when you use the ./configure script; without any -D... compiler options you'd have nothing now.

**Comment by sipa** [comment]
@gmaxwell The default is already everything on, but only when you use the ./configure script; without any -D... compiler options you'd have nothing now.

**Comment by gmaxwell** [comment]
Needs rebase  (maybe after introducing a generic fallback? :P )

**Comment by sipa** [comment]
Rebased, and made it so that building without -D flags results in building everything (they're DISABLE_FIELD_n macros).

**Comment by sipa** [comment]
I think this is ready.

@theuni Care to have another look?

**Comment by gmaxwell** [comment]
ACK b6f01a8ff24d0269a741a0b627f9cc19a605b906

On my slow laptop it still takes 5 seconds each compiling the files that have nothing enabled in them, but it's still a big improvement.

**Comment by sipa** [comment]
@gmaxwell Added a commit that should improve upon that (and another one to remove some spurious includes).

**Comment by gmaxwell** [comment]
ACK 1e3abc31062c1178cdff4cdccf93392d7bd269f4   much better.

**Pull request merged**
