### PR TITLE
Reorder expression to avoid unsigned underflow

### PR DESCRIPTION
**Pull request by sipa**
See https://github.com/bitcoin/bitcoin/pull/23114#issuecomment-929597411

### CODE REVIEW

**Comment by naumenkogs** [comment]
ACK

**Comment by gmaxwell** [comment]
I am obligated to express dubiousness about tools that make people falsely believe there is a problem with that code, but the change is fine too. :P

**Comment by sipa** [comment]
Going to close this; see https://github.com/bitcoin/bitcoin/pull/23114#issuecomment-930726177 and subsequent discussion.

**Comment by theuni** [comment]
There are two more instances of unnecessary wraps detected by ubsan, but they appear to be equally harmless to me:
```patch
diff --git a/src/minisketch/src/sketch_impl.h b/src/minisketch/src/sketch_impl.h
index 4547b742f2..88d889ae79 100644
--- a/src/minisketch/src/sketch_impl.h
+++ b/src/minisketch/src/sketch_impl.h
@@ -26,7 +26,7 @@ void PolyMod(const std::vector<typename F::Elem>& mod, std::vector<typename F::E
         if (term != 0) {
             typename F::Multiplier mul(field, term);
             for (size_t x = 0; x < mod.size() - 1; ++x) {
-                val[val.size() - modsize + 1 + x] ^= mul(mod[x]);
+                val[val.size() + 1 + x - modsize] ^= mul(mod[x]);
             }
         }
     }
@@ -51,7 +51,7 @@ void DivMod(const std::vector<typename F::Elem>& mod, std::vector<typename F::El
         if (term != 0) {
             typename F::Multiplier mul(field, term);
             for (size_t x = 0; x < mod.size() - 1; ++x) {
-                val[val.size() - modsize + 1 + x] ^= mul(mod[x]);
+                val[val.size() +1 + x - modsize] ^= mul(mod[x]);
             }
         }
     }
```

**Pull request closed without merging**
