### PR TITLE
Add minisketch-vs image to repo

### PR DESCRIPTION
**Pull request by jnewbery**
https://people.xiph.org/~greg/minisketch-vs.png returns 404

### CODE REVIEW

**Comment by sipa** [comment]
ping @gmaxwell

**Comment by gmaxwell** [comment]
The xiph.org web server and all data on it was lost.  But I believe it was a scaled copy of this file: https://files.catbox.moe/xznhd6.png  I don't have anywhere to host it anymore.

**Comment by jnewbery** [comment]
ok, I've scaled that image and added it to the repo. Let me know what you think.

**Comment by sipa** [comment]
ACK c87acceabc2de23e23de9373ed71f92f12a0a320

**Comment by gmaxwell** [comment]
ACK c87acceabc2de23e23de9373ed71f92f12a0a320

**Comment by naumenkogs** [comment]
ACK c87acce

**Pull request merged**
