### PR TITLE
A few improvements to prepare for subtree in Bitcoin Core

### PR DESCRIPTION
**Pull request by sipa**
This includes various build system and compatibility improvements discovered in the process of subtreeing this into Bitcoin Core (see https://github.com/bitcoin/bitcoin/pull/21859).

* A few compatibility issues suggested [here](https://github.com/bitcoin/bitcoin/pull/21859#issuecomment-832736638) by sipsorcery.
* Support for __builtin_clz equivalent on MSVC
* Support for CPUID detection on MSVC
* Prevent internal symbols from being exported
* Make old MinGW CI work (-all-static instead of -static needed).

### CODE REVIEW

**Comment by sipa** [comment]
cc @sipsorcery

**Comment by gmaxwell** [comment]
I believe ```_WIN32``` is the standard rather than ```WIN32```.

**Comment by sipsorcery** [comment]
> I believe `_WIN32` is the standard rather than `WIN32`.

I used `WIN32` as it was the first existing example I came across in the Bitcoin Core code base. Taking a closer look both `WIN32` and `_WIN32` are both in common use. That being said, and as @gmaxwell alludes to, `_WIN32` is the preprocessor define [preset](https://docs.microsoft.com/en-us/cpp/preprocessor/predefined-macros?view=msvc-160) by the `msvc` compiler.

For other projects I usually use `_MSVC_VER` to differentiate an `msvc` build from a `gcc` or other compiler build. Not that relevant here since the defines are being used to select headers rather than compiler features.

I personally have no objections to either using `WIN32` or `_WIN32`. In either case the intent is clear.

**Comment by gmaxwell** [comment]
I believe that _WIN32 is set by the compiler on windows, WIN32 is only set if you have some header that sets it or a build environment that does.

https://docs.microsoft.com/en-us/cpp/preprocessor/predefined-macros?redirectedfrom=MSDN&view=msvc-160

Googling around I see commits in some open source projects changing from WIN32 to _WIN32, and I see that some projects check for either or.  I don't see any changing from _WIN32 to WIN32.  So I think checking if either is set or just checking _WIN32 alone is the most reliable choice.  As far as bitcoin core goes, it has a relatively limited support of build environments, so whatever works is fine.  It's better though if library code tends to be more portable.

**Comment by sipa** [comment]
Changed to _WIN32, and also switched `unistd.h` for `stddef.h` (as I think it's just for `size_t`).

**Comment by gmaxwell** [comment]
utACK 4721111ca4f50b5137b721bb04e97fcdd0c35984  this should be tested by someone on MSVC.

**Comment by sipa** [comment]
I'm testing this in https://github.com/bitcoin/bitcoin/pull/21859, so still making changes.

**Comment by sipa** [comment]
This is ready.

**Comment by gmaxwell** [comment]
utACK 1e96b67fcfcc19981a819b0fdc830010618c2c9a   (I also tested it, but not with mingw or msvc, so it doesn't count)

**Comment by gmaxwell** [comment]
okay, I tested mingw32 too.

**Pull request merged**
